name: Deploy FastAPI to Amazon ECR

on:
  push:
    branches: [ "feature/infra" ]

env:
  ECR_REGISTRY: ${{ secrets.AWS_ECR_REGISTRY }}
  ECR_REPOSITORY: srg/fastapi
  IMAGE_TAG: ${{ github.sha }}

permissions:
  contents: read

jobs:
  build-and-push-to-ecr:
    name: Build and Push
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # (Optional) Docker layer cache can be added here if needed

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and Push Docker image to ECR
        run: |
          IMAGE_TAG=${{ github.sha }}
          ECR_REGISTRY=${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY=srg/fastapi
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

      - name: Update kubeconfig
        run: aws eks update-kubeconfig --region ap-northeast-2 --name eks-cluster

      - name: Update fastapi Deployment image
        run: |
          IMAGE_TAG=${{ github.sha }}
          ECR_REGISTRY=${{ steps.login-ecr.outputs.registry }}
          kubectl set image deployment/fastapi fastapi=$ECR_REGISTRY/srg/fastapi:$IMAGE_TAG --namespace=default
          kubectl rollout status deployment/fastapi --namespace=default
